### ISSUE TITLE
Dashboard, site ids and a "fix" for README/docker compose

### ISSUE THREAD

**Issue by Dan-Sun** [riesinger/plausible-exporter#5]
Hey

I just came across your exporter and I would like to give it a shot. Couple of questions:
1. Do you have a dashboard for grafana already?
2. How to add another website? Just like: PLAUSIBLE_SITE_IDS=website1,website2
3. README needs to be changed in `image: ghcr.io/riesinger/plausible-exporter:main`, not latest.

Thanks and have a good night
Dan

**Comment by jboesh** [comment]
I was looking for the same thing, would be nice if you could add / share the grafana dashboard and add support for multiple websites! Keep up the good work.

**Comment by riesinger** [comment]
Hey 👋  Thanks for your feedback! 
I've created a small demo dashboard [in this branch](https://github.com/riesinger/plausible-exporter/blob/grafana-template/examples/grafana-dashboard.json). I would be happy about some feedback on that 🙂 

As for adding multiple sites, you've got that right. You can just join them with a comma. I will update the README shortly

Yes, this incorrect Docker tag was a great catch! I actually did want to create a `latest` tag, but TBH I just forgot

**Comment by Dan-Sun** [comment]
> Do I need to set a metrics_path? like this? /plausible-exporter
> 
> Or what is advised?
> 
> ```
> - job_name: exportplausible
>   metrics_path: /plausible-exporter
>   static_configs:
>   - targets:
>     - 192.168.1.1:8086
> ```

Nearly! It's ...
```
  - job_name: 'plausible'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:8080']
```

Check with `curl 192.168.1.1:8086/metrics`.


Thank you both. It works and I will test it now first.

**Comment by riesinger** [comment]
hi @jboesh 👋 @Dan-Sun is right, his config works. But since the `/metrics` endpoint is the default for Prometheus exporters, you don't even have to specify that.
I will merge the branch with the example dashboard now :)
